/**
 * Copyright (C) 2018 IOLITE GmbH, All rights reserved.
 * Created: 02.07.2018
 */
 
package de.iolite.drivers.gesture;

import javax.annotation.Nonnull;

/**
 * Holds constants of property profiles and types.
 * This class has been generated by the <i>IOLITE Driver Development Kit</i>.
 */
@SuppressWarnings("checkstyle:ConstantName")
public final class DriverConstants {
	
	/**
	 * Holds the name of the {@code recognizedGesture} property type.
	 */
	@Nonnull
	public static final String PROPERTY_recognizedGesture_NAME = "recognizedGesture";
	
	/**
	 * Holds the namespace URI of the {@code recognizedGesture} property type.
	 */
	@Nonnull
	public static final String PROPERTY_recognizedGesture_NAMESPACE = "http://iolite.de";
	
	/**
	 * Holds the identifier of the {@code recognizedGesture} property type.
	 */
	@Nonnull
	public static final String PROPERTY_recognizedGesture_ID = "http://iolite.de#recognizedGesture";
	
	/**
	 * Holds the name of the {@code GestureSensor} property profile.
	 */
	@Nonnull
	public static final String PROFILE_GestureSensor_NAME = "GestureSensor";

	/**
	 * Holds the namespace URI of the {@code GestureSensor} property profile.
	 */
	@Nonnull
	public static final String PROFILE_GestureSensor_NAMESPACE = "http://iolite.de";

	/**
	 * Holds the identifier of the {@code GestureSensor} property profile.
	 */
	@Nonnull
	public static final String PROFILE_GestureSensor_ID = "http://iolite.de#GestureSensor";
	
		/**
	 * Holds the name of the {@code recognizedGesture} property in the {@code GestureSensor} profile.
	 */
	@Nonnull
	public static final String PROFILE_PROPERTY_GestureSensor_recognizedGesture_NAME = PROPERTY_recognizedGesture_NAME;
	
	/**
	 * Holds the namespace URI of the {@code recognizedGesture} property in the {@code GestureSensor} profile.
	 */
	@Nonnull
	public static final String PROFILE_PROPERTY_GestureSensor_recognizedGesture_NAMESPACE = PROPERTY_recognizedGesture_NAMESPACE;
	
	/**
	 * Holds the identifier of the {@code recognizedGesture} property in the {@code GestureSensor} profile.
	 */
	@Nonnull
	public static final String PROFILE_PROPERTY_GestureSensor_recognizedGesture_ID = PROPERTY_recognizedGesture_ID;
		
	/**
	 * Holds all property IDs.
	 */
	@Nonnull
	private static final String[] PROPERTY_IDs = new String[] {
		PROPERTY_recognizedGesture_ID};
	
	/**
	 * Returns all property identifiers of this utility.
	 *
	 * @return all property identifiers held by this utility, never {@code null}
	 */
	@Nonnull
	public static String[] getPropertyIDs() {
		final String[] propertyIDs = new String[PROPERTY_IDs.length];
		System.arraycopy(PROPERTY_IDs, 0, propertyIDs, 0, PROPERTY_IDs.length);
		return propertyIDs;
	}
	
	private DriverConstants() {
		// hide constructor of utility class
		throw new UnsupportedOperationException();
	}
}
